### ISSUE TITLE
Add .nvmrc file to track node version

### ISSUE THREAD

**Issue by kee-oth** [FatimaGC/Portfolio#6]
Let's add an `.nvmrc` file to the root of the project with the appropriate node version specified in it. This will let developers know what version of node they should use when working on the project. And as a bonus, any developer using `nvm` will just need to run `nvm use` in the Terminal to switch to the right version.

The file contents should just be this:
```16.18.1```

The documentation for reference:
https://github.com/nvm-sh/nvm#nvmrc

**Comment by FatimaGC** [comment]
Added .nvmrc file
